apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nfs-pv-1
  labels:
    tier: storage
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: nfs-pv1
  nfs:
    path: "/srv/nfs/kubetesting/storage"
    server: 192.168.50.100
