kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        instance: {{ .Release.Name }}        
    spec:
      serviceAccountName: {{ .Release.Name }}-sa # name of service account created in rbac.yaml
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: nfs-provisioner-v
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # do not change
              value: {{ .Values.provisioner }}  # SAME AS PROVISONER NAME VALUE IN STORAGECLASS
            - name: NFS_SERVER # do not change
              value: {{ .Values.nfs.server }} # Ip of the NFS SERVER
            - name: NFS_PATH # do not change
              value: {{ .Values.nfs.path }} # path to nfs directory setup
      volumes:
       - name: nfs-provisioner-v # same as volumemouts name
         nfs:
           server: {{ .Values.nfs.server }}
           path: {{ .Values.nfs.path }}
