apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-nfs-dynamic # IMPORTANT pvc needs to mention this name
provisioner: dynamic-provisioner # name can be anything
parameters:
  archiveOnDelete: "false"
