{{ if .Values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }} # IMPORTANT pvc needs to mention this name
provisioner: {{ .Values.provisioner }} # name can be anything
parameters:
  archiveOnDelete: "false"
{{ end -}}
