apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
  labels:
    tier: storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: storageclass-nfs
  nfs:
    path: "/srv/nfs/kubedata/volume1"
    server: 192.168.50.100
