---
  - name: Create metallb-system k8s namespace
    k8s:
      kubeconfig: /home/vagrant/.kube/config
      name: metallb-system
      api_version: v1
      kind: Namespace
      state: present

#  - name: Create k8s kubernetes-dashboard namespace
#    k8s:
#        kubeconfig: /home/vagrant/.kube/config
#        name: kubernetes-dashboard
#        api_version: v1
#        kind: Namespace
#        state: present
