---

  - name: Install the package "unzip"
    apt:
     name: unzip

  - name: Download AWS CLI version 2
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
      dest: /tmp/awscliv2.zip

  - name: Unarchive file 
    unarchive:
        src: /tmp/awscliv2.zip
        dest: /home/vagrant/
        remote_src: yes

  - name: Installing CLI
    shell:  ./aws/install --update
    become: yes

