apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  nfs-pvc-1
  labels:
    tier: storage
    app: app-storage
spec:
  storageClassName: nfs-storageclass
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
