apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
  labels:
    tier: storage
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: nfs-pv2
  nfs:
    path: "/srv/nfs/kubetesting/storage"
    server: 192.168.50.100
