apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  nfs-pvc-2
  labels:
    tier: storage
    app: app-storage
spec:
  storageClassName: nfs-pv2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
