---
- name: "Create tmp directory"
  file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755
  tags: metallb

- name: "Install MetalLB"
  shell: "kubectl apply -f {{ metallb_yaml_url }}"
  become: yes
  become_method: sudo
  become_user: vagrant
  tags: metallb

- name: "Create configmap file"
  template:
    src: metallb-layer-2-config.yml.j2
    dest: "{{ tmp_dir }}/metallb-layer-2-config.yml"
  tags: metallb

- name: "Create MetalLB secrete in kubernetes"
  shell: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
  become: yes
  become_method: sudo
  become_user: vagrant
  tags: metallb
  
- name: "Create MetalLB configmap in kubernetes"
  shell: "kubectl apply -f {{ tmp_dir }}/metallb-layer-2-config.yml"
  become: yes
  become_method: sudo
  become_user: vagrant
  tags: metallb

- name: "Clean-up"
  file:
    path: "{{ tmp_dir }}"
    state: absent
  ignore_errors: yes
  tags: metallb
