---

- name: Install kubectl
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

- name: Make the kubectl binary executable.
  shell: chmod +x ./kubectl

- name: Move the binary in to your PATH
  shell: mv ./kubectl /usr/local/bin/kubectl
  become: yes

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /kube-config/config  /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config




- name: Installing Helm
  shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3

- name: Make the helm binary executable.
  shell: chmod 700 get_helm.sh

- name: Move the binary in to your PATH
  shell: ./get_helm.sh








  





