---

- name: Install kubectl
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

- name: Make the kubectl binary executable.
  shell: chmod +x ./kubectl

- name: Move the binary in to your PATH
  shell: mv ./kubectl /usr/local/bin/kubectl
  become: yes


- name: Setup kube.config - Create Directory
  file:
   path: /home/vagrant/.kube
   state: directory
   mode: "u=rw,g=wx,o=rwx"
   recurse: yes

- name: Copy kube.config 
  copy:
     src: /kube-config/config
     dest: /home/vagrant/.kube/config
     owner: vagrant
     backup: yes


- name: Installing Helm
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '700'

- name: Move the binary in to your PATH
  shell: /tmp/get_helm.sh








  





