---
  - name: Install helm chart from a git repo specifying path
    helm:
      host: localhost
      chart:
        source:
          type: git
          location: https://github.com/helm/charts.git
          path: stable/memcached
      state: present
      name: my-memcached
      namespace: default
