apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-internal
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress_rules.prom.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress_rules.prom.serviceName }}
          servicePort: {{ .Values.ingress_rules.prom.servicePort }}

  - host: {{ .Values.ingress_rules.mailhog.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress_rules.mailhog.serviceName }}
          servicePort: {{ .Values.ingress_rules.mailhog.servicePort }}

  - host: {{ .Values.ingress_rules.grafana.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress_rules.grafana.serviceName }}
          servicePort: {{ .Values.ingress_rules.grafana.servicePort }}

  - host: {{ .Values.ingress_rules.dashboard.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress_rules.dashboard.serviceName }}
          servicePort: {{ .Values.ingress_rules.dashboard.servicePort }}
