---

    - name: docker swarm deploy azurite containers
      shell: docker stack deploy --compose-file /docker/azurite/docker-compose.yaml azurite

    
    - name: docker swarm deploy minio containers
      shell: docker stack deploy --compose-file /docker/minio/docker-compose.yaml minio